# prometheus/prometheus.yml — minimal scrape and alert rule load
global:
  scrape_interval: 5s

rule_files:
  - /etc/prometheus/alerts.yml

scrape_configs:
  - job_name: 'demo-app'
    metrics_path: /metrics
    static_configs:
      - targets: ['app:8000']
